FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

EXPOSE 3000

ENV NODE_ENV=development
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
