# Generated by Django 6.0.3 on 2026-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supperadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='access_level',
            field=models.CharField(choices=[('low', 'Low Access'), ('medium', 'Medium Access'), ('high', 'High Access'), ('full', 'Full Access')], default='low', max_length=20),
        ),
    ]
