# Generated by Django 6.0.4 on 2026-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supperadmin', '0002_role_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Users'), ('orders', 'Orders'), ('products', 'Products'), ('recipes', 'Recipes'), ('blogs', 'Blogs'), ('consultations', 'Consultations'), ('nutritionists', 'Nutritionists'), ('notifications', 'Notifications'), ('reports', 'Reports'), ('events', 'Events')], max_length=30),
        ),
    ]
