# Generated by Django 6.0.4 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supperadmin", "0004_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard"),
                    ("users", "Users"),
                    ("orders", "Orders"),
                    ("products", "Products"),
                    ("recipes", "Recipes"),
                    ("blogs", "Blogs"),
                    ("consultations", "Consultations"),
                    ("nutritionists", "Nutritionists"),
                    ("notifications", "Notifications"),
                    ("reports", "Reports"),
                    ("events", "Events"),
                    ("gifts", "Gifts"),
                ],
                max_length=30,
            ),
        ),
    ]
