# Generated by Django 6.0.3 on 2026-04-08 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('member', 'Member')], default='guest', max_length=10)),
                ('wellness_interests', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_communication', models.CharField(default='email', max_length=50)),
                ('notification_preferences', models.CharField(default='all', max_length=50)),
                ('activate_immediately', models.BooleanField(default=False)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('send_password_setup', models.BooleanField(default=False)),
                ('allow_notifications', models.BooleanField(default=True)),
                ('is_verified_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communityuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityUserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='communityuser.communityuser')),
            ],
        ),
    ]
