# Generated by Django 6.0.4 on 2026-04-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityuser', '0001_initial'),
        ('consultant', '0005_rename_health_goal_consultationbooking_primary_gaol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('choose_section', models.CharField(max_length=100)),
                ('primary_goal', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('additional_message', models.TextField(blank=True)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('diet_restriction', models.CharField(blank=True, max_length=255)),
                ('focus_area', models.CharField(blank=True, max_length=100)),
                ('journey_goal', models.CharField(blank=True, max_length=100)),
                ('lifestyle_activity', models.CharField(blank=True, max_length=100)),
                ('primary_wellness_goal', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultant.consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
