# Generated by Django 6.0.4 on 2026-04-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityuser', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
