# Generated by Django 6.0.4 on 2026-04-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0004_availability_blockeddate_breaktime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationbooking',
            old_name='health_goal',
            new_name='primary_gaol',
        ),
    ]
