# Generated by Django 6.0.4 on 2026-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0005_rename_health_goal_consultationbooking_primary_gaol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationbooking',
            old_name='conditions',
            new_name='buckweath_journy_goal',
        ),
        migrations.RenameField(
            model_name='consultationbooking',
            old_name='primary_gaol',
            new_name='diet_preferences',
        ),
        migrations.RenameField(
            model_name='consultationbooking',
            old_name='notes',
            new_name='message',
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='focuses_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='lifestyle_activity_leavel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='primary_wellness_goal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
