# Generated by Django 6.0.4 on 2026-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0007_rename_typo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationbooking',
            name='session_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call'), ('chat', 'Chat')], default='video', max_length=30),
        ),
    ]
