# Generated by Django 6.0.4 on 2026-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0009_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
