# Generated by Django 6.0.4 on 2026-05-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0012_consultationbooking_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='rejected_consultants',
            field=models.ManyToManyField(blank=True, related_name='rejected_consultation_bookings', to='consultant.consultant'),
        ),
        migrations.AlterField(
            model_name='consultationbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('needs_reschedule', 'Needs Reschedule')], default='pending', max_length=20),
        ),
    ]
