# Generated by Django 6.0.4 on 2026-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('ALERT', 'Alert'), ('REMINDER', 'Reminder'), ('PROMOTIONAL', 'Promotional')], default='SYSTEM', max_length=20)),
                ('target_role', models.CharField(choices=[('ALL', 'All Users'), ('admin', 'Admin'), ('internal_staff', 'Internal Staff'), ('consultant', 'Consultant'), ('community_user', 'Community User')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
