# Generated by Django 6.0.3 on 2026-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('internal_staff', 'Internal Staff'), ('consultant', 'Consultant'), ('community_user', 'Community User')], default='community_user', max_length=20),
        ),
    ]
