# Generated by Django 6.0.3 on 2026-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INTERNAL_STAFF', 'Internal Staff'), ('CONSULTANT', 'Consultant'), ('COMMUNITY_USER', 'Community User')], default='COMMUNITY_USER', max_length=20),
        ),
    ]
