# Generated by Django 6.0.5 on 2026-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_price_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charged_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='charged_currency',
            field=models.CharField(default='SAR', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_country_snapshot',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
