# Generated by Django 6.0.3 on 2026-04-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_gender_alter_user_role'),
        ('supperadmin', '0002_role_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='supperadmin.role'),
        ),
    ]
