# Generated by Django 6.0.3 on 2026-04-08 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('languages_spoken', models.CharField(max_length=255)),
                ('experience_areas', models.CharField(max_length=255)),
                ('session_type', models.CharField(max_length=225)),
                ('consiltation_fee', models.PositiveIntegerField()),
                ('session_duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
