# Generated by Django 6.0.3 on 2026-04-08 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_subtitle', models.CharField(blank=True, max_length=180, null=True)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('seed', 'Seed'), ('supplement', 'Supplement'), ('other', 'Other')], default='other', max_length=30)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('short_description', models.CharField(max_length=150)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('key_ingredients', models.TextField(blank=True, null=True)),
                ('health_benefits', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('INR', 'INR (₹)'), ('AED', 'AED (د.إ)')], default='USD', max_length=3)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_alert', models.PositiveIntegerField(default=5)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('allow_orders_when_out_of_stock', models.BooleanField(default=False)),
                ('enable_low_stock_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
