# Generated by Django 6.0.3 on 2026-04-10 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_excerpt', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('wellness', 'Wellness'), ('healthy_living', 'Healthy Living'), ('diet_tips', 'Diet Tips'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=30)),
                ('reading_time_minutes', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blogs/cover_images/')),
                ('content', models.TextField()),
                ('mark_as_featured', models.BooleanField(default=False)),
                ('publish_schedule', models.CharField(choices=[('immediate', 'Publish Immediately'), ('scheduled', 'Scheduled')], default='immediate', max_length=20)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('show_in_community_blog', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blog.blogtag')),
            ],
        ),
    ]
