import type { BackendClientItem } from "./clientTypes";

export const backendClients: BackendClientItem[] = [
  {
    id: "client-michael-chen",
    name: "Michael Chen",
    age: 32,
    gender: "Male",
    avatar: "",
    status: "Active",
    goal: "Weight Loss",
    allergies: ["Nuts", "Dairy"],
    dietPreference: "Vegetarian",
    lastConsultation: "2 days ago",
    planName: "Buckwheat Diet Plan",
    activeSince: "Started 3 weeks ago",
    currentWeight: "185 lbs",
    targetWeight: "165 lbs",
    bmi: "25.1",
    latestNotes:
      '"Client showing good progress with buckwheat incorporation. Reduced processed food intake significantly."',
    healthSummary: "Steady progress with portion control, higher satiety, and more consistent meal timing.",
    weightLost: "8 lbs",
    adherence: 85,
    progressSummary: "40% towards goal",
    email: "michael.chen@zawadi.test",
    phone: "+1 202 555 0142",
    nextSession: "April 25, 2026 - 10:30 AM",
  },
  {
    id: "client-emma-rodriguez",
    name: "Emma Rodriguez",
    age: 28,
    gender: "Female",
    avatar: "",
    status: "Follow-up Due",
    goal: "General Health",
    allergies: ["None"],
    dietPreference: "Gluten-Free",
    lastConsultation: "1 week ago",
    planName: "Custom Buckwheat Plan",
    activeSince: "Started 5 weeks ago",
    currentWeight: "142 lbs",
    targetWeight: "138 lbs",
    bmi: "22.4",
    latestNotes:
      '"Digestion is improving and energy levels are more stable. Needs help staying consistent with evening meals."',
    healthSummary: "Good routine during weekdays, but still misses structured dinners on busy days.",
    weightLost: "3 lbs",
    adherence: 72,
    progressSummary: "60% towards goal",
    email: "emma.rodriguez@zawadi.test",
    phone: "+1 202 555 0164",
    nextSession: "April 23, 2026 - 4:00 PM",
  },
  {
    id: "client-david-thompson",
    name: "David Thompson",
    age: 45,
    gender: "Male",
    avatar: "",
    status: "High Priority",
    goal: "Muscle Gain",
    allergies: ["Shellfish"],
    dietPreference: "High Protein",
    lastConsultation: "Today",
    planName: "Protein-Rich Buckwheat",
    activeSince: "Started 2 weeks ago",
    currentWeight: "176 lbs",
    targetWeight: "184 lbs",
    bmi: "24.7",
    latestNotes:
      '"Needs tighter protein distribution through the day. Recovery meals are inconsistent after workouts."',
    healthSummary: "Training frequency is strong, but nutrition timing and post-workout recovery need support.",
    weightLost: "N/A",
    adherence: 58,
    progressSummary: "25% towards goal",
    email: "david.thompson@zawadi.test",
    phone: "+1 202 555 0178",
    nextSession: "April 24, 2026 - 1:00 PM",
  },
  {
    id: "client-sophia-johnson",
    name: "Sophia Johnson",
    age: 34,
    gender: "Female",
    avatar: "",
    status: "New",
    goal: "Digestive Health",
    allergies: ["Soy"],
    dietPreference: "Low FODMAP",
    lastConsultation: "Yesterday",
    planName: "Digestive Reset Plan",
    activeSince: "Started 2 days ago",
    currentWeight: "149 lbs",
    targetWeight: "145 lbs",
    bmi: "23.0",
    latestNotes:
      '"New onboarding completed. Food log started, and first week plan shared with symptom tracker."',
    healthSummary: "Early-stage plan focused on symptom tracking, anti-inflammatory foods, and consistency.",
    weightLost: "1 lb",
    adherence: 91,
    progressSummary: "15% towards goal",
    email: "sophia.johnson@zawadi.test",
    phone: "+1 202 555 0192",
    nextSession: "April 26, 2026 - 11:15 AM",
  },
];
