# Generated by Django 6.0.3 on 2026-04-08 11:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('short_description', models.TextField()),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('other', 'Other')], default='other', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('prep_time_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cooking_time_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='recipes/cover_images/')),
                ('health_benefits', models.TextField(blank=True, null=True)),
                ('buckwheat_wellness_value', models.TextField(blank=True, null=True)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_high_fiber', models.BooleanField(default=False)),
                ('is_weight_management', models.BooleanField(default=False)),
                ('is_energy_boosting', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_in_community', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=120)),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('cups', 'cups'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('piece', 'piece')], default='cups', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_no'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status'], name='recipes_rec_status_d54da6_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_featured'], name='recipes_rec_is_feat_75f06e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['show_in_community'], name='recipes_rec_show_in_eb3da2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='recipes_rec_categor_081389_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together={('recipe', 'step_no')},
        ),
    ]
