# Generated by Django 6.0.5 on 2026-05-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_cover_image'),
        ('recipes', '0007_favoriterecipe'),
    ]

    operations = [
    ]
