# Generated by Django 6.0.5 on 2026-05-19 11:29

from django.db import migrations
import datetime


def seed_forward(apps, schema_editor):
    Currency = apps.get_model("tax", "Currency")
    CountryConfig = apps.get_model("tax", "CountryConfig")
    TaxCategory = apps.get_model("tax", "TaxCategory")
    TaxRate = apps.get_model("tax", "TaxRate")

    # Currencies
    sar = Currency.objects.create(code="SAR", name="Saudi Riyal", symbol="SAR", decimal_places=2)
    aed = Currency.objects.create(code="AED", name="UAE Dirham", symbol="AED", decimal_places=2)
    bhd = Currency.objects.create(code="BHD", name="Bahraini Dinar", symbol="BHD", decimal_places=3)
    omr = Currency.objects.create(code="OMR", name="Omani Rial", symbol="OMR", decimal_places=3)

    # Country → currency mapping
    CountryConfig.objects.create(country="SA", name="Saudi Arabia", currency=sar)
    CountryConfig.objects.create(country="AE", name="United Arab Emirates", currency=aed)
    CountryConfig.objects.create(country="BH", name="Bahrain", currency=bhd)
    CountryConfig.objects.create(country="OM", name="Oman", currency=omr)

    # Tax categories
    standard = TaxCategory.objects.create(name="Standard Rate", code="STANDARD", description="Standard VAT rate")
    zero = TaxCategory.objects.create(name="Zero-Rated", code="ZERO", description="Zero-rated goods (e.g. basic food staples)")
    TaxCategory.objects.create(name="Exempt", code="EXEMPT", description="VAT exempt goods")

    # Saudi Arabia rates (effective 2020-07-01 when VAT rose to 15%)
    effective = datetime.date(2020, 7, 1)
    TaxRate.objects.create(country="SA", tax_category=standard, rate="0.1500", name="Saudi VAT Standard Rate 15%", effective_from=effective)
    TaxRate.objects.create(country="SA", tax_category=zero, rate="0.0000", name="Saudi VAT Zero-Rated", effective_from=effective)


def seed_reverse(apps, schema_editor):
    Currency = apps.get_model("tax", "Currency")
    CountryConfig = apps.get_model("tax", "CountryConfig")
    TaxCategory = apps.get_model("tax", "TaxCategory")
    TaxRate = apps.get_model("tax", "TaxRate")
    TaxRate.objects.all().delete()
    TaxCategory.objects.all().delete()
    CountryConfig.objects.all().delete()
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_forward, seed_reverse),
    ]
