# Generated by Django 6.0.5 on 2026-05-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryconfig',
            options={'ordering': ['country'], 'verbose_name_plural': 'country configurations'},
        ),
    ]
