# Generated by Django 6.0.4 on 2026-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_agenda_highlights_event_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
