# Generated by Django 6.0.4 on 2026-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date_remove_legacy_datetime_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date', '-start_time']},
        ),
    ]
