# Generated by Django 6.0.4 on 2026-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_variant_unit_and_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant_name',
            new_name='variant_value',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
    ]
