# Generated by Django 6.0.5 on 2026-05-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_image'),
        ('product', '0007_productimage'),
    ]

    operations = [
    ]
