# Generated by Django 6.0.5 on 2026-05-19 11:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productimage_image_to_urlfield'),
        ('tax', '0003_add_product_country_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCountryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='tax.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_prices', to='product.product')),
            ],
            options={
                'ordering': ['country'],
                'constraints': [models.UniqueConstraint(fields=('product', 'country'), name='unique_product_country_price')],
            },
        ),
    ]
