# Generated by Django 6.0.5 on 2026-05-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_seed_product_country_prices'),
        ('tax', '0003_add_product_country_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='tax.taxcategory'),
        ),
    ]
