# Generated by Django 6.0.5 on 2026-05-19 11:42

from django.db import migrations


def backfill_forward(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    TaxCategory = apps.get_model("tax", "TaxCategory")
    try:
        standard = TaxCategory.objects.get(code="STANDARD")
    except TaxCategory.DoesNotExist:
        return
    Product.objects.filter(tax_category__isnull=True).update(tax_category=standard)


def backfill_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_add_tax_category_nullable"),
        ("tax", "0002_seed_data"),
    ]

    operations = [
        migrations.RunPython(backfill_forward, backfill_reverse),
    ]
